# --- DOCUMENTATION GRID ---
Documentation: {
  grid-rows: 2
  style: {
    stroke-dash: 0
    fill: "transparent"
  }

  explanation_weapon: |md
    ###  Weapon Registry

    ####  OpFor (Eastern)
    - **R-60M** (AA-8 Aphid)
    - **R-27R/T** (AA-10 Alamo)
    - **R-73** (AA-11 Archer)
    - **R-77** (AA-12 Adder)
    - **R-77-1** (AA-12B)
    - **R-37M** (AA-13 Axehead)

    - **Kh-25** (AS-10 Karen)
    - **Kh-29L/T** (AS-14 Kedge)
    - **Kh-31P** (AS-17 Krypton)
    - **Kh-59** (AS-13 Kingbolt)
    - **FAB-250/500**
    - **S-5 / S-8 / S-13**

    - **S-75** (SA-2 Guideline)
    - **S-125** (SA-3 Goa)
    - **2K12 Kub** (SA-6 Gainful)
    - **9K33 Osa** (SA-8 Gecko)
    - **9K37 Buk** (SA-11 Gadfly)
    - **S-300P** (SA-10 Grumble)
    - **9K330 Tor** (SA-15 Gauntlet)

    - **9K38 Igla** (SA-18 Grouse)

    #### BluFor (Western)

     - **AIM-9L/M** (Sidewinder)
    - **AIM-9X** (Sidewinder)
    - **AIM-7F/M** (Sparrow)
    - **AIM-120C/D** (AMRAAM)
    - **AIM-54C** (Phoenix)
    - **Meteor** (BVRAAM

    - **AGM-65D/G**
    - **AGM-88C**
    - **AGM-84H/K** (SLAM-ER)
    - **GBU-12/10/24** (Paveway)
    - **Mk-82/83/84**
    - **Hydra 70**

    - **MIM-23** (Hawk)
    - **MIM-104** (Patriot)
    - **MIM-72** (Chaparral)
    - **NASAMS**
    - **RIM-66/67**
    - **Crotale NG**

    - **FIM-92A/C** (Stinger)
    - **FIM-43** (Redeye)
  |

  explanation_helicopter: |md
    ### Helicopter Registry
    ####  OpFor (Eastern)
    - **Mi-8/17** (Hip) 
    - **Mi-24V/P** (Hind)
    - **Mi-28N** (Havoc)
    - **Ka-50/52** (Hokum)

    #### BluFor (Western)
    - **UH-1H** (Huey)
    - **AH-1W/Z** (Super Cobra/Viper)
    - **AH-64A/D** (Apache)
    - **OH-58D** (Kiowa Warrior)
  |

  explanation_plane: |md
    ### Plane Registry
    #### OpFor (Eastern)
    - **MiG-21bis** (Fishbed)
    - **MiG-23MLD** (Flogger-K)
    - **MiG-29** (Fulcrum-A)
    - **MiG-29SMT** (Fulcrum-E)
    - **MiG-31BM** (Foxhound)
    - **Su-24M** (Fencer-D)
    - **Su-25SM3** (Frogfoot)
    - **Su-27** (Flanker-B)
    - **Su-27SM** (Flanker-J)
    - **Su-30SM** (Flanker-H)
    - **Su-30SM2** (Flanker-H)
    - **Su-33** (Flanker-D)
    - **Tu-95MS** (Bear-H)

    #### BluFor (Western)
    - **F-4E** (Phantom II)
    - **F-14B** (Tomcat)
    - **F-15C** (Eagle)
    - **F-15E** (Strike Eagle)
    - **F-15EX** (Eagle II)
    - **F-16C Block 50** (Viper)
    - **F-16V** (Viper)
    - **F/A-18C** (Hornet)
    - **F/A-18E/F** (Super Hornet)
    - **A-10C** (Warthog)
    - **F-111F** (Aardvark)
    - **B-52H** (Stratofortress)
    - **Tornado IDS/ADV**

  |

  explanation_radar: |md
    ### Radar Registry
    #### OpFor (Eastern)
    **Propelled (Mobile Units)**
    - **9K33 Osa** (SA-8 Gecko)
    - **9K35 Strela-10** (SA-13 Gopher)
    - **9K22 Tunguska** (SA-19 Grison)
    - **9K330 Tor-M1** (SA-15 Gauntlet)
    - **9K37 Buk-M2** (SA-11 Gadfly)
    - **9K22 Pantsir-S1** (SA-22 Greyhound)
    - **S-300PS / 5P85D**

    **Stationary (Fixed/Towed)**
    - **S-75** (SA-2 Guideline)
    - **S-125** (SA-3 Goa)
    - **S-300P Site**
    - **SNR-75** (Fan Song)

    **Fighter/Interceptor Radars**
    - **RP-22SM "Sapfir-21"**
    - **Sapfir-23MLD**
    - **N019 "Rubin"**
    - **N019MP**
    - **N007 "Zaslon-M"**
    - **N001 "Mech"**
    - **N001VEP**
    - **N011M "Bars"**
    - **N035 "Irbis-E"**

    **Attack/Bomber/Heli Radars**
    - **Kopyo-25**
    - **Orion-A**
    - **Obzor-MS**
    - **N025 "Almaz-280"**
    - **FH01 Arbalet-52**

    #### BluFor (Western)
    **Propelled (Mobile Units)**
    - **MIM-72 Chaparral**
    - **M1097 Avenger**
    - **Flakpanzer Gepard**
    - **M6 Linebacker**
    - **Roland**
    - **MIM-104 Patriot TEL**

    **Stationary (Fixed/Towed)**
    - **MIM-23 Hawk**
    - **MIM-104 Patriot Site**
    - **NASAMS Launcher**
    - **Crotale NG**
    - **AN/MPQ-53**

    **Fighter/Attack Radars**
    - **AN/APQ-120**
    - **AN/AWG-9 / APG-71**
    - **AN/APG-63(V)1**
    - **AN/APG-70**
    - **AN/APG-82(V)1**
    - **AN/APG-68(V)9**
    - **AN/APG-83 SABR**
    - **AN/APG-65 / 73**
    - **AN/APG-79**
    - **AN/APQ-174**
    - **AN/APG-66H**

    **Heavy/Heli Radars**
    - **AN/APQ-166**
    - **AN/APG-78 Longbow**
    - **MMS (Mast Mounted Sight)**
  |
}

# Top-level explanation stays above or to the side
Main_Logic: {
  explanation: |md
    # Prototype Singleton
    - All objects (vehicles) created upon game start and stored in a static map.
    - Inside the map, it points to instances in-memory for quick read.
    - **Flyable** includes: helicopters, missiles, dumb bombs, guided bombs, planes, drones.
    - Cloned via `.clone()` for live entity spawning.
    - ...
    - search radars are the only kind of radar which can paint a target onto the screen
    - this includes airborne radars, and groundbased radars
    - as a radar detects a target, it will first make sure its not dupelicating the detection
    - then it will add itself to the list of targets tracking on the vehicle
    - any vehicle with 1 or more targets tracking will be painted
    - ...
    - bullets, dumb bombs, and unguided rockets are classified as flyable objects with no pilot, no turn rate, a maxed out radar (this is so we can ensure target detection incase the target goes defensive but because the object is unguided it wouldnt be afflicted by this, its on a set ballistic  flight path) and a target
    - ALL entities compute if they can hit the target, if the answer is no they will linger for a few seconds on the ui
    - and then despawn the object
  |
}

# Class Definitions

MapIcon: {
  shape: class
  -String name
  -String iconPath

  -float32 x
  -float32 y
  -float32 z
}

Vehicle: {
  shape: class
  -string id

  -nullable Pilot pilot
  -nullable Radar radar
  -nullable Loadout loadout

  -uint16 maxSpeed
  -uint16 speed
  -float8 direction

  -uint8 radarCrossSection
  -uint8 irSignature
  -uint8 lineOfSightDetection
  -uint8 rwrDetection

  "-Array<Vehicle> beingTrackedBy"

  "+abstract tick()"
  "+abstract move(MapIcon target)"
  "+abstract avoidIncoming()"
  "+abstact engage(Vehicle target)"
}

DriveAble: {
  shape: class

  +tick()
  +move(MapIcon target)
  +avoidIncoming()
  +engage(Vehicle target)
}

Flyable: {
  shape: class

  -bool despawnIfCantHitTarget

  -uint8 maximumAltitude

  -uint wepTimer
  -uint wepOverload
  -uint8 turnRate
  -uint8 optimalTurnSpeed
  -uint8 turnSpeedBleed

  -float8 azimuth

  -uint8 fuelTime
  -uint16 weight
  -uint8 liftCoefficent
  -uint8 dragCoefficent
  -uint16 thrustDelta

  -uint8 chaffCount
  -uint8 flareCount

  +tick()
  +move(MapIcon target)
  +avoidIncoming()
  +engage(Vehicle target)
}

Pilot: {
  shape: class

  -uint8 awareness
  -uint8 pilotCount
  -uint8 skillLevel

  +int8 calculateBonusDetection()
}

Radar: {
  shape: class
  -string name
  -string id

  -bool offensive
  -bool hasAtLeastOneViableTarget

  -uint8 precisionFactor
  -uint8 maximumRange
  -uint8 searchAreaLeft
  -uint8 maxSearchAzimuth
  -uint8 minSearchAzimuth

  -uint8 curX
  -uint8 curY

  -uint8 scanChunkSize

  -uint8 datalinkRange
  -Flyable datalinkChild

  "+Array<Vehicle> scanChunk()"
  "+abstract Vehicle selectBestTarget(Array<Vehicle>)"
  "+Array<Vehicle> hitableTargets(Weapon selectedWeapon)": we will dumb this down and make it only compute with one weapon per tick
}

InfraredSeeker: {
  shape: class

  -nullable Vehicle target
  -uint4 flareResistanceFront
  -uint4 flareResistanceRear
  -uint4 flareResistanceSide

  "+Vehicle selectBestTarget(Array<Vehicle>)"
}

antiRadiationSeeker: {
  shape: class
  "+Vehicle selectBestTarget(Array<Vehicle>)"
}

SearchRadar: {
  shape: class
  -uint8 detectionLingerTime
  "-Array<Tuple<vehicle target, uint8 lastDetection>> trackedTargets"

  -bool AESA
}

SemiActiveRadar: {
  shape: class
  -nullable Vehicle target
  -nullable Radar hostRadar

  "+Vehicle selectBestTarget(Array<Vehicle>)"
}

ActiveRadar: {
  shape: class

  "+Vehicle selectBestTarget(Array<Vehicle>)"
}

Loadout: {
  shape: class
  "-Array<HardPoints> hardpoints"
  -int16 loadoutWeight

  +void calculateLoadoutWeight()
  +int16 getLoadoutWeight()
  +Weapon calculateBestWeaponToEngageWith(Vehicle target)
}

HardPoint: {
  shape: class
  -nullable Weapon equippedWeapon
  "-Array<Weapon> options"

  "+Array<string> getWeaponOptionNames()"
  +Weapon getEquippedWeapon()
}

Weapon: {
  shape: class
  -uint8 capacity
  -string name
  -string id
  -uint8 dropWeight

  +Flyable deploy(Vehicle parent, nullable Vehicle target)

  +string getName()
  +string getID()
  +uint8 getDropWeight()
  +uint8 getCapacity()
  +void setName(string name)
  +void setID(string id)
  +void setDropWeight(uint8 dropWeight)
}

# Connection definitions
MapIcon -> Vehicle: composite of

Vehicle -> Flyable: composite of
Vehicle -> DriveAble: composite of

Vehicle -> Pilot: has a
Vehicle -> Radar: has a
Vehicle -> Loadout: has a

Radar -> SemiActiveRadar: composite of
Radar -> SearchRadar: composite of
Radar -> InfraredSeeker: composite of

SemiActiveRadar -> antiRadiationSeeker: composite of
SemiActiveRadar -> ActiveRadar: composite of

Loadout -> HardPoint: has a

HardPoint -> Weapon: has a
